export const BATTLE_FACT_TYPES = Object.freeze({
    TERRAIN_FOREST: "TERRAIN_FOREST",
    TERRAIN_DEEP_FOREST: "TERRAIN_DEEP_FOREST",
    TERRAIN_WETLAND: "TERRAIN_WETLAND",
    TERRAIN_HILL: "TERRAIN_HILL",
    HIGH_GROUND: "HIGH_GROUND",
    ENEMY_LARGE_BODY: "ENEMY_LARGE_BODY",
    ENEMY_HEAVY_EQUIPMENT: "ENEMY_HEAVY_EQUIPMENT",
    ENEMY_DEPLOYMENT_CONSTRAINED: "ENEMY_DEPLOYMENT_CONSTRAINED",
    ENEMY_RESERVE_PRESENT: "ENEMY_RESERVE_PRESENT",
    HUMAN_LOCAL_POWER_PRESENT: "HUMAN_LOCAL_POWER_PRESENT",
    ENEMY_LOCAL_POWER_PRESENT: "ENEMY_LOCAL_POWER_PRESENT"
});

export const BATTLE_CAUSE_CATEGORIES = Object.freeze({
    OBSERVATION: "OBSERVATION",
    POSITIONING: "POSITIONING",
    MOBILITY: "MOBILITY",
    DEPLOYMENT: "DEPLOYMENT",
    INITIATIVE: "INITIATIVE",
    COHESION: "COHESION",
    ATTRITION: "ATTRITION",
    COLLAPSE: "COLLAPSE"
});

export const BATTLE_CAUSE_TYPES = Object.freeze({
    DEPLOYMENT_CONSTRAINED: "DEPLOYMENT_CONSTRAINED",
    MOVEMENT_CONSTRAINED: "MOVEMENT_CONSTRAINED",
    ENEMY_RESERVE_HELD_BACK: "ENEMY_RESERVE_HELD_BACK",
    TERRAIN_ADVANTAGE: "TERRAIN_ADVANTAGE",
    LOCAL_SUPERIORITY: "LOCAL_SUPERIORITY",
    HUMAN_PRESSURE_ADVANTAGE: "HUMAN_PRESSURE_ADVANTAGE",
    VANGUARD_ISOLATED: "VANGUARD_ISOLATED"
});

export const BATTLE_CONSEQUENCE_TYPES = Object.freeze({
    SUPPORT_DELAYED: "SUPPORT_DELAYED"
});

export const BATTLE_CAUSAL_EVENT_TYPES = Object.freeze({
    ENEMY_DEPLOYMENT_LIMITED: "ENEMY_DEPLOYMENT_LIMITED",
    ENEMY_MOVEMENT_LIMITED: "ENEMY_MOVEMENT_LIMITED",
    ENEMY_RESERVE_NOT_COMMITTED: "ENEMY_RESERVE_NOT_COMMITTED",
    TERRAIN_POSITION_ADVANTAGE: "TERRAIN_POSITION_ADVANTAGE",
    HUMAN_LOCAL_SUPERIORITY_ESTABLISHED: "HUMAN_LOCAL_SUPERIORITY_ESTABLISHED",
    HUMAN_PRESSURE_MAINTAINED: "HUMAN_PRESSURE_MAINTAINED",
    ENEMY_VANGUARD_ISOLATED: "ENEMY_VANGUARD_ISOLATED"
});

export const BATTLEFIELD_CAPABILITY_KEYS = Object.freeze([
    "movement",
    "visibility",
    "concealment",
    "frontage",
    "elevation",
    "footing",
    "retreat",
    "combustibility"
]);

export const BATTLE_STATE_LEVELS = Object.freeze({
    DEPLOYMENT: Object.freeze(["NORMAL", "SLIGHTLY_CONSTRAINED", "CONSTRAINED", "SEVERELY_CONSTRAINED"]),
    COHESION: Object.freeze(["ORDERED", "SHAKEN", "DISORDERED", "BROKEN"]),
    COLLAPSE: Object.freeze(["STABLE", "WITHDRAWING", "ROUTING", "GENERAL_ROUT"])
});
