export const BATTLE_RESOLUTION_PHASES = Object.freeze({
    NORMAL_OUTCOME_PENDING: "NORMAL_OUTCOME_PENDING",
    OPPORTUNITY_PENDING: "OPPORTUNITY_PENDING",
    FORTUNE_RESOLVED: "FORTUNE_RESOLVED",
    FINALIZED: "FINALIZED"
});

export const BATTLE_OPPORTUNITY_TYPES = Object.freeze({
    EXTEND_NORMAL_OUTCOME: "EXTEND_NORMAL_OUTCOME"
});

export const BATTLE_FORTUNE_RESULTS = Object.freeze({
    NORMAL_OUTCOME_MAINTAINED: "NORMAL_OUTCOME_MAINTAINED",
    DECISIVE_SUCCESS: "DECISIVE_SUCCESS"
});

export const BATTLE_RESOLUTION_ERRORS = Object.freeze({
    SNAPSHOT_REQUIRED: "BATTLE_RESOLUTION_SNAPSHOT_REQUIRED",
    NORMAL_OUTCOME_REQUIRED: "BATTLE_NORMAL_OUTCOME_REQUIRED",
    OPPORTUNITY_NOT_PENDING: "BATTLE_OPPORTUNITY_NOT_PENDING",
    OPPORTUNITY_DECLINED: "BATTLE_OPPORTUNITY_DECLINED",
    OPPORTUNITY_ALREADY_RESOLVED: "BATTLE_OPPORTUNITY_ALREADY_RESOLVED",
    EMBER_POLICY_REQUIRED: "BATTLE_EMBER_COST_POLICY_REQUIRED",
    INVALID_EMBER_COST: "BATTLE_EMBER_COST_INVALID",
    EMBER_SYSTEM_REQUIRED: "BATTLE_EMBER_SYSTEM_REQUIRED",
    INSUFFICIENT_EMBER: "BATTLE_EMBER_INSUFFICIENT",
    GAMEPLAY_RNG_REQUIRED: "BATTLE_GAMEPLAY_RNG_REQUIRED",
    ALREADY_COMMITTED: "BATTLE_EMBER_ALREADY_COMMITTED",
    FORTUNE_ALREADY_RESOLVED: "BATTLE_FORTUNE_ALREADY_RESOLVED",
    FINAL_RESULT_REQUIRED: "BATTLE_FINAL_RESULT_REQUIRED"
});
