export const BATTLE_FACT_TYPES = Object.freeze({
    TERRAIN_FOREST: "TERRAIN_FOREST",
    TERRAIN_DEEP_FOREST: "TERRAIN_DEEP_FOREST",
    TERRAIN_WETLAND: "TERRAIN_WETLAND",
    TERRAIN_HILL: "TERRAIN_HILL",
    HIGH_GROUND: "HIGH_GROUND",
    ENEMY_LARGE_BODY: "ENEMY_LARGE_BODY",
    ENEMY_HEAVY_EQUIPMENT: "ENEMY_HEAVY_EQUIPMENT",
    ENEMY_DEPLOYMENT_CONSTRAINED: "ENEMY_DEPLOYMENT_CONSTRAINED",
    ENEMY_RESERVE_PRESENT: "ENEMY_RESERVE_PRESENT",
    HUMAN_LOCAL_POWER_PRESENT: "HUMAN_LOCAL_POWER_PRESENT",
    ENEMY_LOCAL_POWER_PRESENT: "ENEMY_LOCAL_POWER_PRESENT"
});

export const BATTLE_CAUSE_TYPES = Object.freeze({
    DEPLOYMENT_CONSTRAINED: "DEPLOYMENT_CONSTRAINED",
    ENEMY_RESERVE_HELD_BACK: "ENEMY_RESERVE_HELD_BACK",
    TERRAIN_ADVANTAGE: "TERRAIN_ADVANTAGE",
    LOCAL_SUPERIORITY: "LOCAL_SUPERIORITY",
    HUMAN_PRESSURE_ADVANTAGE: "HUMAN_PRESSURE_ADVANTAGE"
});

export const BATTLE_CAUSAL_EVENT_TYPES = Object.freeze({
    ENEMY_DEPLOYMENT_LIMITED: "ENEMY_DEPLOYMENT_LIMITED",
    ENEMY_RESERVE_NOT_COMMITTED: "ENEMY_RESERVE_NOT_COMMITTED",
    TERRAIN_POSITION_ADVANTAGE: "TERRAIN_POSITION_ADVANTAGE",
    HUMAN_LOCAL_SUPERIORITY_ESTABLISHED: "HUMAN_LOCAL_SUPERIORITY_ESTABLISHED",
    HUMAN_PRESSURE_MAINTAINED: "HUMAN_PRESSURE_MAINTAINED"
});
