export const TRIAL_PHASES = Object.freeze({
    SETUP: "SETUP",
    DEPLOYMENT: "DEPLOYMENT",
    BATTLE: "BATTLE",
    RESULT: "RESULT"
});

export const TRIAL_ROUTE_PLAN_STATUSES = Object.freeze({
    UNDECIDED: "UNDECIDED",
    INTERCEPT: "INTERCEPT",
    SKIP: "SKIP"
});

export const TRIAL_PLAN_REASONS = Object.freeze({
    UNKNOWN_ROUTE: "UNKNOWN_ROUTE",
    INVALID_INTERCEPT_CELL: "INVALID_INTERCEPT_CELL",
    CELL_NOT_ON_ROUTE: "CELL_NOT_ON_ROUTE",
    INTERCEPTION_NOT_ALLOWED: "INTERCEPTION_NOT_ALLOWED",
    BLOCK_ALREADY_PLANNED: "BLOCK_ALREADY_PLANNED",
    INVALID_DEFENSE_ALLOCATION: "INVALID_DEFENSE_ALLOCATION",
    DEFENSE_BUDGET_EXCEEDED: "DEFENSE_BUDGET_EXCEEDED",
    ALREADY_CONFIRMED: "ALREADY_CONFIRMED",
    NO_CONFIRMED_PLAN: "NO_CONFIRMED_PLAN",
    PLAN_ALREADY_ACTIVATED: "PLAN_ALREADY_ACTIVATED",
    PLAN_DEFENSE_EXCEEDS_AVAILABLE: "PLAN_DEFENSE_EXCEEDS_AVAILABLE",
    INVALID_CONFIRMED_PLAN: "INVALID_CONFIRMED_PLAN",
    PLAN_NOT_ACTIVATED: "PLAN_NOT_ACTIVATED",
    NO_PENDING_BATTLES: "NO_PENDING_BATTLES",
    BATTLE_ALREADY_ACTIVE: "BATTLE_ALREADY_ACTIVE",
    INVALID_BATTLE_QUEUE_ITEM: "INVALID_BATTLE_QUEUE_ITEM",
    NO_ACTIVE_BATTLE: "NO_ACTIVE_BATTLE",
    BATTLE_ALREADY_RESOLVED: "BATTLE_ALREADY_RESOLVED",
    INVALID_CURRENT_BATTLE: "INVALID_CURRENT_BATTLE",
    NO_RESOLVED_BATTLE: "NO_RESOLVED_BATTLE",
    MISSING_BATTLE_RESULT: "MISSING_BATTLE_RESULT",
    INVALID_TRAVERSAL_ROUTE: "INVALID_TRAVERSAL_ROUTE",
    TRAVERSAL_ALREADY_APPLIED: "TRAVERSAL_ALREADY_APPLIED",
    TRAVERSAL_NOT_APPLIED: "TRAVERSAL_NOT_APPLIED",
    MISSING_TRAVERSAL_RESULT: "MISSING_TRAVERSAL_RESULT",
    BATTLE_TRANSITION_ALREADY_APPLIED: "BATTLE_TRANSITION_ALREADY_APPLIED",
    INVALID_BATTLE_SEQUENCE: "INVALID_BATTLE_SEQUENCE"
});

export const TRIAL_BATTLE_STATUSES = Object.freeze({
    PENDING: "PENDING",
    ACTIVE: "ACTIVE",
    RESOLVED: "RESOLVED"
});

export const MODIFIER_PHASES = Object.freeze({
    DEPLOYMENT_LIMIT: 100,
    MULTIPLIER: 200
});

export const MODIFIER_TARGETS = Object.freeze({
    HUMAN_INTERCEPTION: "HUMAN_INTERCEPTION",
    ENEMY_SUPPRESSION: "ENEMY_SUPPRESSION"
});

export const MODIFIER_OPERATIONS = Object.freeze({
    LIMIT_OVERFLOW: "LIMIT_OVERFLOW",
    MULTIPLY: "MULTIPLY"
});

export const TRIAL_TERRAIN_EFFECTS = Object.freeze({
    FOREST_DEPLOYMENT: "FOREST_DEPLOYMENT",
    DEEP_FOREST_DEPLOYMENT: "DEEP_FOREST_DEPLOYMENT",
    WETLAND_EXIT: "WETLAND_EXIT",
    DESERT_EXIT: "DESERT_EXIT",
    HIGH_GROUND: "HIGH_GROUND"
});

export const TRIAL_OUTCOMES = Object.freeze({
    REPEL: "REPEL",
    BREAKTHROUGH: "BREAKTHROUGH",
    EXACT: "EXACT"
});

export const TRIAL_MODIFIER_I18N_KEYS = Object.freeze({
    [TRIAL_TERRAIN_EFFECTS.FOREST_DEPLOYMENT]: "UI_TRIAL_MOD_FOREST_DEPLOYMENT",
    [TRIAL_TERRAIN_EFFECTS.DEEP_FOREST_DEPLOYMENT]: "UI_TRIAL_MOD_DEEP_FOREST_DEPLOYMENT",
    [TRIAL_TERRAIN_EFFECTS.WETLAND_EXIT]: "UI_TRIAL_MOD_WETLAND_EXIT",
    [TRIAL_TERRAIN_EFFECTS.DESERT_EXIT]: "UI_TRIAL_MOD_DESERT_EXIT",
    [TRIAL_TERRAIN_EFFECTS.HIGH_GROUND]: "UI_TRIAL_MOD_HIGH_GROUND"
});

export const DEFAULT_TRIAL_RULES = Object.freeze({
    defenseConversionRate: 5,
    suppressionConversionRate: 5,
    highGroundMultiplier: 1.2,
    wetlandExitMultiplier: 0.8,
    desertExitMultiplier: 0.9,
    forestDeployment: Object.freeze({ threshold: 40, overflowEfficiency: 0.5 }),
    // Phase 1検証用の注入可能な仮値。確定バランス値ではない。
    deepForestDeployment: Object.freeze({ threshold: 30, overflowEfficiency: 0.35 })
});
