export const INVESTIGATION_LOCALIZATION = Object.freeze({
    ja: Object.freeze({
        INVESTIGATION_FACET_DIRECTION: "方角",
        INVESTIGATION_FACET_SCALE: "規模",
        INVESTIGATION_FACET_PHYSIQUE: "体格",
        INVESTIGATION_FACET_EQUIPMENT: "装備",
        INVESTIGATION_FACET_MOVEMENT: "行動",
        INVESTIGATION_FACET_TERRAIN: "地形",
        INVESTIGATION_FACET_UNKNOWN: "観測",

        INVESTIGATION_SOURCE_FOOTPRINTS_TITLE: "足跡の調査",
        INVESTIGATION_SOURCE_FOOTPRINTS_BODY: "辺境で、人ならざるものの足跡が確認された。痕跡から分かる範囲を記録する。",
        INVESTIGATION_SOURCE_CAMP_REMAINS_TITLE: "野営跡の調査",
        INVESTIGATION_SOURCE_CAMP_REMAINS_BODY: "放棄された野営跡が見つかった。残された痕跡から、滞在していた集団の様子を推し量る。",
        INVESTIGATION_SOURCE_SCOUT_SIGHTING_TITLE: "斥候の目撃報告",
        INVESTIGATION_SOURCE_SCOUT_SIGHTING_BODY: "斥候が遠方に亜人の姿を認めた。確認できた特徴だけが報告された。",
        INVESTIGATION_SOURCE_UNKNOWN_TITLE: "調査報告",
        INVESTIGATION_SOURCE_UNKNOWN_BODY: "断片的な痕跡が報告された。",

        INVESTIGATION_TAG_NORTH_ACTIVITY: "北方で活動の痕跡",
        INVESTIGATION_TAG_NORTH_EAST_ACTIVITY: "北東方面で活動の痕跡",
        INVESTIGATION_TAG_EAST_ACTIVITY: "東方で活動の痕跡",
        INVESTIGATION_TAG_SOUTH_EAST_ACTIVITY: "南東方面で活動の痕跡",
        INVESTIGATION_TAG_SOUTH_ACTIVITY: "南方で活動の痕跡",
        INVESTIGATION_TAG_SOUTH_WEST_ACTIVITY: "南西方面で活動の痕跡",
        INVESTIGATION_TAG_WEST_ACTIVITY: "西方で活動の痕跡",
        INVESTIGATION_TAG_NORTH_WEST_ACTIVITY: "北西方面で活動の痕跡",
        INVESTIGATION_TAG_LARGE_BODY_PRESENT: "大柄な個体を含む",
        INVESTIGATION_TAG_SMALL_BODY_PRESENT: "小柄な個体を含む",
        INVESTIGATION_TAG_METAL_ARMOR: "金属製の防具を使用",
        INVESTIGATION_TAG_LONG_WEAPON: "長柄の武器を所持",
        INVESTIGATION_TAG_PROJECTILE_WEAPON: "投射武器を所持",
        INVESTIGATION_TAG_NIGHT_MOVEMENT: "夜間にも移動",
        INVESTIGATION_TAG_BAGGAGE_PRESENT: "荷駄を伴う",
        INVESTIGATION_TAG_FOREST_ACTIVITY: "森林内での活動に慣れている",
        INVESTIGATION_TAG_SCALE_SMALL: "小規模な集団",
        INVESTIGATION_TAG_SCALE_MEDIUM: "一定規模の集団",
        INVESTIGATION_TAG_SCALE_LARGE: "大規模な集団",
        INVESTIGATION_TAG_SCALE_VERY_LARGE: "極めて大規模な集団"
    }),
    en: Object.freeze({
        INVESTIGATION_FACET_DIRECTION: "Direction",
        INVESTIGATION_FACET_SCALE: "Scale",
        INVESTIGATION_FACET_PHYSIQUE: "Physique",
        INVESTIGATION_FACET_EQUIPMENT: "Equipment",
        INVESTIGATION_FACET_MOVEMENT: "Movement",
        INVESTIGATION_FACET_TERRAIN: "Terrain",
        INVESTIGATION_FACET_UNKNOWN: "Observation",

        INVESTIGATION_SOURCE_FOOTPRINTS_TITLE: "Tracks",
        INVESTIGATION_SOURCE_FOOTPRINTS_BODY: "Tracks left by something other than humans were found on the frontier. Only what can be supported by the traces is recorded.",
        INVESTIGATION_SOURCE_CAMP_REMAINS_TITLE: "Abandoned Camp",
        INVESTIGATION_SOURCE_CAMP_REMAINS_BODY: "An abandoned camp was found. The remains offer a limited view of the group that stayed there.",
        INVESTIGATION_SOURCE_SCOUT_SIGHTING_TITLE: "Scout Sighting",
        INVESTIGATION_SOURCE_SCOUT_SIGHTING_BODY: "Scouts sighted demihumans in the distance and reported only the features they could confirm.",
        INVESTIGATION_SOURCE_UNKNOWN_TITLE: "Investigation Report",
        INVESTIGATION_SOURCE_UNKNOWN_BODY: "Fragmentary traces were reported.",

        INVESTIGATION_TAG_NORTH_ACTIVITY: "Activity to the north",
        INVESTIGATION_TAG_NORTH_EAST_ACTIVITY: "Activity to the northeast",
        INVESTIGATION_TAG_EAST_ACTIVITY: "Activity to the east",
        INVESTIGATION_TAG_SOUTH_EAST_ACTIVITY: "Activity to the southeast",
        INVESTIGATION_TAG_SOUTH_ACTIVITY: "Activity to the south",
        INVESTIGATION_TAG_SOUTH_WEST_ACTIVITY: "Activity to the southwest",
        INVESTIGATION_TAG_WEST_ACTIVITY: "Activity to the west",
        INVESTIGATION_TAG_NORTH_WEST_ACTIVITY: "Activity to the northwest",
        INVESTIGATION_TAG_LARGE_BODY_PRESENT: "Large-bodied individuals present",
        INVESTIGATION_TAG_SMALL_BODY_PRESENT: "Small-bodied individuals present",
        INVESTIGATION_TAG_METAL_ARMOR: "Metal armor in use",
        INVESTIGATION_TAG_LONG_WEAPON: "Long weapons carried",
        INVESTIGATION_TAG_PROJECTILE_WEAPON: "Projectile weapons carried",
        INVESTIGATION_TAG_NIGHT_MOVEMENT: "Movement continues at night",
        INVESTIGATION_TAG_BAGGAGE_PRESENT: "Baggage train present",
        INVESTIGATION_TAG_FOREST_ACTIVITY: "Accustomed to moving through forest",
        INVESTIGATION_TAG_SCALE_SMALL: "Small group",
        INVESTIGATION_TAG_SCALE_MEDIUM: "Moderate-sized group",
        INVESTIGATION_TAG_SCALE_LARGE: "Large group",
        INVESTIGATION_TAG_SCALE_VERY_LARGE: "Very large group"
    })
});

export default INVESTIGATION_LOCALIZATION;
