export const INVESTIGATION_LOCALIZATION = Object.freeze({
    ja: Object.freeze({
        INVESTIGATION_FACET_DIRECTION: "方角",
        INVESTIGATION_FACET_SCALE: "規模",
        INVESTIGATION_FACET_PHYSIQUE: "体格",
        INVESTIGATION_FACET_EQUIPMENT: "装備",
        INVESTIGATION_FACET_MOVEMENT: "行動",
        INVESTIGATION_FACET_TERRAIN: "地形",
        INVESTIGATION_FACET_UNKNOWN: "観測",

        INVESTIGATION_SOURCE_FOOTPRINTS_TITLE: "足跡の調査",
        INVESTIGATION_SOURCE_FOOTPRINTS_BODY: "辺境で、人ならざるものの足跡が確認された。痕跡から分かる範囲を記録する。",
        INVESTIGATION_SOURCE_CAMP_REMAINS_TITLE: "野営跡の調査",
        INVESTIGATION_SOURCE_CAMP_REMAINS_BODY: "放棄された野営跡が見つかった。残された痕跡から、滞在していた集団の様子を推し量る。",
        INVESTIGATION_SOURCE_SCOUT_SIGHTING_TITLE: "斥候の目撃報告",
        INVESTIGATION_SOURCE_SCOUT_SIGHTING_BODY: "斥候が遠方に亜人の姿を認めた。確認できた特徴だけが報告された。",
        INVESTIGATION_SOURCE_UNKNOWN_TITLE: "調査報告",
        INVESTIGATION_SOURCE_UNKNOWN_BODY: "断片的な痕跡が報告された。",

        INVESTIGATION_TAG_NORTH_ACTIVITY: "北方で活動の痕跡",
        INVESTIGATION_TAG_NORTH_EAST_ACTIVITY: "北東方面で活動の痕跡",
        INVESTIGATION_TAG_EAST_ACTIVITY: "東方で活動の痕跡",
        INVESTIGATION_TAG_SOUTH_EAST_ACTIVITY: "南東方面で活動の痕跡",
        INVESTIGATION_TAG_SOUTH_ACTIVITY: "南方で活動の痕跡",
        INVESTIGATION_TAG_SOUTH_WEST_ACTIVITY: "南西方面で活動の痕跡",
        INVESTIGATION_TAG_WEST_ACTIVITY: "西方で活動の痕跡",
        INVESTIGATION_TAG_NORTH_WEST_ACTIVITY: "北西方面で活動の痕跡",
        INVESTIGATION_TAG_LARGE_BODY_PRESENT: "大柄な個体を含む",
        INVESTIGATION_TAG_SMALL_BODY_PRESENT: "小柄な個体を含む",
        INVESTIGATION_TAG_METAL_ARMOR: "金属製の防具を使用",
        INVESTIGATION_TAG_LONG_WEAPON: "長柄の武器を所持",
        INVESTIGATION_TAG_PROJECTILE_WEAPON: "投射武器を所持",
        INVESTIGATION_TAG_NIGHT_MOVEMENT: "夜間にも移動",
        INVESTIGATION_TAG_BAGGAGE_PRESENT: "荷駄を伴う",
        INVESTIGATION_TAG_FOREST_ACTIVITY: "森林内での活動に慣れている",
        INVESTIGATION_TAG_SCALE_SMALL: "小規模な集団",
        INVESTIGATION_TAG_SCALE_MEDIUM: "一定規模の集団",
        INVESTIGATION_TAG_SCALE_LARGE: "大規模な集団",
        INVESTIGATION_TAG_SCALE_VERY_LARGE: "極めて大規模な集団",

        INVESTIGATION_NARRATIVE_FOOTPRINTS_INTRO: "辺境で、人ならざるものの足跡が見つかった。",
        INVESTIGATION_NARRATIVE_CAMP_REMAINS_INTRO: "放棄された野営跡から、滞在していた集団の痕跡が拾い上げられた。",
        INVESTIGATION_NARRATIVE_SCOUT_SIGHTING_INTRO: "斥候が遠方の亜人を目撃し、確認できた特徴を持ち帰った。",
        INVESTIGATION_NARRATIVE_GENERIC_INTRO: "断片的な痕跡が確認された。",
        INVESTIGATION_NARRATIVE_TAG_NORTH_ACTIVITY: "痕跡は北方に集中している。",
        INVESTIGATION_NARRATIVE_TAG_NORTH_EAST_ACTIVITY: "痕跡は北東方面に集中している。",
        INVESTIGATION_NARRATIVE_TAG_EAST_ACTIVITY: "痕跡は東方に集中している。",
        INVESTIGATION_NARRATIVE_TAG_SOUTH_EAST_ACTIVITY: "痕跡は南東方面に集中している。",
        INVESTIGATION_NARRATIVE_TAG_SOUTH_ACTIVITY: "痕跡は南方に集中している。",
        INVESTIGATION_NARRATIVE_TAG_SOUTH_WEST_ACTIVITY: "痕跡は南西方面に集中している。",
        INVESTIGATION_NARRATIVE_TAG_WEST_ACTIVITY: "痕跡は西方に集中している。",
        INVESTIGATION_NARRATIVE_TAG_NORTH_WEST_ACTIVITY: "痕跡は北西方面に集中している。",
        INVESTIGATION_NARRATIVE_TAG_LARGE_BODY_PRESENT: "中には、明らかに大柄な個体のものと思われる痕跡が混じる。",
        INVESTIGATION_NARRATIVE_TAG_SMALL_BODY_PRESENT: "小柄な個体のものと思われる痕跡も混じっている。",
        INVESTIGATION_NARRATIVE_TAG_METAL_ARMOR: "金属製の防具を用いている形跡がある。",
        INVESTIGATION_NARRATIVE_TAG_LONG_WEAPON: "長柄の武器を携えている形跡がある。",
        INVESTIGATION_NARRATIVE_TAG_PROJECTILE_WEAPON: "投射武器を持つ個体が含まれているようだ。",
        INVESTIGATION_NARRATIVE_TAG_NIGHT_MOVEMENT: "活動は夜間にも続いている。",
        INVESTIGATION_NARRATIVE_TAG_BAGGAGE_PRESENT: "荷駄を伴って移動している形跡がある。",
        INVESTIGATION_NARRATIVE_TAG_FOREST_ACTIVITY: "森林内での移動に慣れている様子がうかがえる。",
        INVESTIGATION_NARRATIVE_TAG_SCALE_SMALL: "残された痕跡は、小規模な集団のものとみられる。",
        INVESTIGATION_NARRATIVE_TAG_SCALE_MEDIUM: "残された痕跡は、一定規模の集団のものとみられる。",
        INVESTIGATION_NARRATIVE_TAG_SCALE_LARGE: "残された痕跡は、大規模な集団のものとみられる。",
        INVESTIGATION_NARRATIVE_TAG_SCALE_VERY_LARGE: "残された痕跡は、極めて大規模な集団のものとみられる。"
    }),
    en: Object.freeze({
        INVESTIGATION_FACET_DIRECTION: "Direction",
        INVESTIGATION_FACET_SCALE: "Scale",
        INVESTIGATION_FACET_PHYSIQUE: "Physique",
        INVESTIGATION_FACET_EQUIPMENT: "Equipment",
        INVESTIGATION_FACET_MOVEMENT: "Movement",
        INVESTIGATION_FACET_TERRAIN: "Terrain",
        INVESTIGATION_FACET_UNKNOWN: "Observation",

        INVESTIGATION_SOURCE_FOOTPRINTS_TITLE: "Tracks",
        INVESTIGATION_SOURCE_FOOTPRINTS_BODY: "Tracks left by something other than humans were found on the frontier. Only what can be supported by the traces is recorded.",
        INVESTIGATION_SOURCE_CAMP_REMAINS_TITLE: "Abandoned Camp",
        INVESTIGATION_SOURCE_CAMP_REMAINS_BODY: "An abandoned camp was found. The remains offer a limited view of the group that stayed there.",
        INVESTIGATION_SOURCE_SCOUT_SIGHTING_TITLE: "Scout Sighting",
        INVESTIGATION_SOURCE_SCOUT_SIGHTING_BODY: "Scouts sighted demihumans in the distance and reported only the features they could confirm.",
        INVESTIGATION_SOURCE_UNKNOWN_TITLE: "Investigation Report",
        INVESTIGATION_SOURCE_UNKNOWN_BODY: "Fragmentary traces were reported.",

        INVESTIGATION_TAG_NORTH_ACTIVITY: "Activity to the north",
        INVESTIGATION_TAG_NORTH_EAST_ACTIVITY: "Activity to the northeast",
        INVESTIGATION_TAG_EAST_ACTIVITY: "Activity to the east",
        INVESTIGATION_TAG_SOUTH_EAST_ACTIVITY: "Activity to the southeast",
        INVESTIGATION_TAG_SOUTH_ACTIVITY: "Activity to the south",
        INVESTIGATION_TAG_SOUTH_WEST_ACTIVITY: "Activity to the southwest",
        INVESTIGATION_TAG_WEST_ACTIVITY: "Activity to the west",
        INVESTIGATION_TAG_NORTH_WEST_ACTIVITY: "Activity to the northwest",
        INVESTIGATION_TAG_LARGE_BODY_PRESENT: "Large-bodied individuals present",
        INVESTIGATION_TAG_SMALL_BODY_PRESENT: "Small-bodied individuals present",
        INVESTIGATION_TAG_METAL_ARMOR: "Metal armor in use",
        INVESTIGATION_TAG_LONG_WEAPON: "Long weapons carried",
        INVESTIGATION_TAG_PROJECTILE_WEAPON: "Projectile weapons carried",
        INVESTIGATION_TAG_NIGHT_MOVEMENT: "Movement continues at night",
        INVESTIGATION_TAG_BAGGAGE_PRESENT: "Baggage train present",
        INVESTIGATION_TAG_FOREST_ACTIVITY: "Accustomed to moving through forest",
        INVESTIGATION_TAG_SCALE_SMALL: "Small group",
        INVESTIGATION_TAG_SCALE_MEDIUM: "Moderate-sized group",
        INVESTIGATION_TAG_SCALE_LARGE: "Large group",
        INVESTIGATION_TAG_SCALE_VERY_LARGE: "Very large group",

        INVESTIGATION_NARRATIVE_FOOTPRINTS_INTRO: "Tracks left by something other than humans were found on the frontier.",
        INVESTIGATION_NARRATIVE_CAMP_REMAINS_INTRO: "An abandoned camp yielded traces of the group that stayed there.",
        INVESTIGATION_NARRATIVE_SCOUT_SIGHTING_INTRO: "Scouts sighted demihumans at a distance and brought back only what they could confirm.",
        INVESTIGATION_NARRATIVE_GENERIC_INTRO: "Fragmentary traces were confirmed.",
        INVESTIGATION_NARRATIVE_TAG_NORTH_ACTIVITY: "The traces are concentrated to the north.",
        INVESTIGATION_NARRATIVE_TAG_NORTH_EAST_ACTIVITY: "The traces are concentrated to the northeast.",
        INVESTIGATION_NARRATIVE_TAG_EAST_ACTIVITY: "The traces are concentrated to the east.",
        INVESTIGATION_NARRATIVE_TAG_SOUTH_EAST_ACTIVITY: "The traces are concentrated to the southeast.",
        INVESTIGATION_NARRATIVE_TAG_SOUTH_ACTIVITY: "The traces are concentrated to the south.",
        INVESTIGATION_NARRATIVE_TAG_SOUTH_WEST_ACTIVITY: "The traces are concentrated to the southwest.",
        INVESTIGATION_NARRATIVE_TAG_WEST_ACTIVITY: "The traces are concentrated to the west.",
        INVESTIGATION_NARRATIVE_TAG_NORTH_WEST_ACTIVITY: "The traces are concentrated to the northwest.",
        INVESTIGATION_NARRATIVE_TAG_LARGE_BODY_PRESENT: "Some traces appear to have been left by notably large-bodied individuals.",
        INVESTIGATION_NARRATIVE_TAG_SMALL_BODY_PRESENT: "Some traces appear to have been left by smaller individuals.",
        INVESTIGATION_NARRATIVE_TAG_METAL_ARMOR: "There are signs that metal armor is in use.",
        INVESTIGATION_NARRATIVE_TAG_LONG_WEAPON: "There are signs that long weapons are being carried.",
        INVESTIGATION_NARRATIVE_TAG_PROJECTILE_WEAPON: "Some individuals appear to carry projectile weapons.",
        INVESTIGATION_NARRATIVE_TAG_NIGHT_MOVEMENT: "Their activity continues at night.",
        INVESTIGATION_NARRATIVE_TAG_BAGGAGE_PRESENT: "There are signs of a baggage train moving with them.",
        INVESTIGATION_NARRATIVE_TAG_FOREST_ACTIVITY: "They appear accustomed to moving through forested ground.",
        INVESTIGATION_NARRATIVE_TAG_SCALE_SMALL: "The traces suggest a small group.",
        INVESTIGATION_NARRATIVE_TAG_SCALE_MEDIUM: "The traces suggest a group of moderate size.",
        INVESTIGATION_NARRATIVE_TAG_SCALE_LARGE: "The traces suggest a large group.",
        INVESTIGATION_NARRATIVE_TAG_SCALE_VERY_LARGE: "The traces suggest a very large group."
    })
});

export default INVESTIGATION_LOCALIZATION;
